#!/bin/csh -f
set loc=`dirname $0`
set nam=`echo $HOST | cut -c1-4`
switch ($HOSTTYPE)
case 'x86_64-linux':
 $loc/conv-c2b-cent $*
 breaksw
case 'FreeBSD':
 $loc/conv-c2b-bsd $*
 breaksw
case 'aarch64-linux':
 if ( $nam == 'cadp' ) then
 $loc/conv-c2b-fugaku $*
 else
 $loc/conv-c2b-zynq $*
 endif
 breaksw
endsw
